default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: task_b_development

test:
  <<: *default
  database: task_b_test

production:
  <<: *default
  database: task_b_production
  username: task_b
  password: <%= ENV['TASK_B_DATABASE_PASSWORD'] %>
